const ADD_USER = "user:ADD_USER";
const GET_USER = "user:GET_USER";
const UPDATE_USER = "user:UPDATE_USER";
const DELETE_USER = "user:DELETE_USER";
const ADD_TO_WISH_LIST = "user:ADD_TO_WISH_LIST";
const DELETE_FROM_WISH_LIST = "user:DELETE_FROM_WISH_LIST";
const GET_WISH_LIST = "user:GET_WISH_LIST";
const LIKE_PRODUCT = "user:LIKE_PRODUCT";
const LIKE_VENDOR = "user:LIKE_VENDOR";
const LIKE_COLLECTION = "user:LIKE_COLLECTION";
const GET_COLLECTION_LIST = "user:GET_COLLECTION_LIST";
const GET_LIKED_PRODUCT = "user:GET_LIKED_PRODUCT";
const GET_LIKED_VENDOR = "user:GET_LIKED_VENDOR";
const UPDATE_PROFILE_USER = "user:UPDATE_PROFILE_USER";
const DELETE_PROFILE_USER = "user:DELETE_PROFILE_USER";
const GET_ALL_USER = "user:GET_ALL_USER";
const GET_USER_BY_ID = "user:GET_USER_BY_ID";
const ARCHIVE_USER = "user:ARCHIVE_USER";
const DISARCHIVE_USER = "user:DISARCHIVE_USER";
const ARCHIVE_PROFILE = "user:ARCHIVE_PROFILE";
const DISARCHIVE_PROFILE = "user:DISARCHIVE_PROFILE";
const SUBSCRIBE = "user:SUBSCRIBE";
const GET_ALL_NOTIFICATION = "user:GET_ALL_NOTIFICATION";
const GET_SELECTED_ITEMS = "user:GET_SELECTED_ITEMS";
const ADD_ITEM_TO_SELECTED_LIST = "user:ADD_ITEM_TO_SELECTED_LIST";
const REMOVE_ITEM_FROM_SELECTED_LIST = "user:REMOVE_ITEM_FROM_SELECTED_LIST";



const ADD_VENDOR = "vendor:ADD_VENDOR";
const GET_VENDOR = "vendor:GET_VENDOR";
const UPDATE_VENDOR = "vendor:UPDATE_VENDOR";
const DELETE_VENDOR = "vendor:DELETE_VENDOR";
const GET_VENDOR_BY_ID = "vendor:GET_VENDOR_BY_ID";
const GET__ALL_VENDOR = "vendor:GET__ALL_VENDOR";
const GET_ALL_CATEGORY_BY_VENDOR = "vendor:GET_ALL_CATEGORY_BY_VENDOR";
const VENDOR_SEARCH = "vendor:VENDOR_SEARCH";
const UPDATE_PROFILE_VENDOR = "vendor:UPDATE_PROFILE_VENDOR";
const DELETE_PROFILE_VENDOR = "vendor:DELETE_PROFILE_VENDOR";
const GET_MOST_LIKED_BRANDS = "vendor:GET_MOST_LIKED_BRANDS";
const ARCHIVE_VENDOR = "vendor:ARCHIVE_VENDOR";
const DISARCHIVE_VENDOR = "vendor:DISARCHIVE_VENDOR";
const ARCHIVE_PROFILE_VENDOR = "vendor:ARCHIVE_PROFILE_VENDOR";
const DISARCHIVE_PROFILE_VENDOR = "vendor:DISARCHIVE_PROFILE_VENDOR";



const ADD_ADMIN = "admin:ADD_ADMIN";
const GET_ADMIN = "admin:GET_ADMIN";
const GET_ADMIN_BY_ID = "admin:GET_ADMIN_BY_ID";
const UPDATE_ADMIN = "admin:UPDATE_ADMIN";
const DELETE_ADMIN = "admin:DELETE_ADMIN";
const GET__ALL_ADMIN = "admin:GET__ALL_ADMIN";



const ADD_PRODUCT = "product:ADD_PRODUCT";
const GET_PRODUCT_BY_ID = "product:GET_PRODUCT_BY_ID";
const UPDATE_PRODUCT = "product:UPDATE_PRODUCT";
const DELETE_PRODUCT = "product:DELETE_PRODUCT";
const ARCHIVE_PRODUCT = "product:ARCHIVE_PRODUCT";
const DISARCHIVE_PRODUCT = "product:DISARCHIVE_PRODUCT";
const GET_ALL_PRODUCT = "product:GET_ALL_PRODUCT";
const GET_ALL_BRAND_ITEMS = "product:GET_ALL_BRAND_ITEMS";
const GET_MOST_LIKED_ITEMS = "product:GET_MOST_LIKED_ITEMS";
const GET_ALL_PRODUCT_BY_VENDOR = "product:GET_ALL_PRODUCT_BY_VENDOR";
const GET_ALL_PRODUCT_BY_CATEGORY = "product:GET_ALL_PRODUCT_BY_CATEGORY";
const GET_ALL_PRODUCT_BY_COLLECTION = "product:GET_ALL_PRODUCT_BY_COLLECTION";
const GET_ALL_PRODUCT_WITH_FILTER = "product:GET_ALL_PRODUCT_WITH_FILTER";
const PRODUCT_SEARCH = "product:PRODUCT_SEARCH";
const ADD_OFFER = "product:ADD_OFFER";
const GET_ALL_OFFER = "product:GET_ALL_OFFER";






const ADD_CATEGORY = "category:ADD_CATEGORY";
const GET_CATEGORY_BY_ID = "category:GET_CATEGORY_BY_ID";
const UPDATE_CATEGORY = "category:UPDATE_CATEGORY";
const DELETE_CATEGORY = "category:DELETE_CATEGORY";
const GET_ALL_CATEGORY = "category:GET_ALL_CATEGORY";
const CATEGORY_SEARCH = "category:CATEGORY_SEARCH";




// const ADD_OFFER = "offer:ADD_OFFER";
// const GET_OFFER_BY_ID = "offer:GET_OFFER_BY_ID";
// const UPDATE_OFFER = "offer:UPDATE_OFFER";
// const DELETE_OFFER = "offer:DELETE_OFFER";
// const GET_ALL_OFFER = "offer:GET_ALL_OFFER";
// const GET_ALL_OFFER_BY_VENDOR = "offer:GET_ALL_OFFER_BY_VENDOR";
// const GET_ALL_OFFER_BY_CATEGORY = "offer:GET_ALL_OFFER_BY_CATEGORY";
// const GET_ALL_PRODUCT_BY_VENDOR_CATEGORY = "offer:GET_ALL_PRODUCT_BY_VENDOR_CATEGORY";




const ADD_COLLECTION= "collection:ADD_COLLECTION";
const GET_COLLECTION_BY_ID = "collection:GET_COLLECTION_BY_ID";
const UPDATE_COLLECTION = "collection:UPDATE_COLLECTION";
const DELETE_COLLECTION = "collection:DELETE_COLLECTION";
const ARCHIVE_COLLECTION = "collection:ARCHIVE_COLLECTION";
const DISARCHIVE_COLLECTION = "collection:DISARCHIVE_COLLECTION";
const GET_ALL_COLLECTION = "collection:GET_ALL_COLLECTION";
const GET_ALL_Brand_COLLECTION = "collection:GET_ALL_Brand_COLLECTION";
const COLLECTION_SEARCH = "collection:COLLECTION_SEARCH";
const GET_MOST_LIKED_COLLECTIONS = "collection:GET_MOST_LIKED_COLLECTIONS";


const ADD_SALE= "sale:ADD_SALE";
const GET_SALE_BY_ID = "sale:GET_SALE_BY_ID";
const UPDATE_SALE = "sale:UPDATE_SALE";
const DELETE_SALE = "sale:DELETE_SALE";
const GET_ALL_SALE = "sale:GET_ALL_SALE";
const SALE_SEARCH = "sale:SALE_SEARCH";
const GET_MOST_LIKED_SALES = "sale:GET_MOST_LIKED_SALES";
const ARCHIVE_SALE = "sale:ARCHIVE_SALE";
const DISARCHIVE_SALE = "sale:DISARCHIVE_SALE";



const ADD_ADVERTISMENT = "advertisment:ADD_ADVERTISMENT";
const GET_ADVERTISMENTS_BY_ID = "advertisment:GET_ADVERTISMENTS_BY_ID";
const UPDATE_ADVERTISMENT = "advertisment:UPDATE_ADVERTISMENT";
const DELETE_ADVERTISMENT = "advertisment:DELETE_ADVERTISMENT";
const GET_ALL_ADVERTISMENT = "advertisment:GET_ALL_ADVERTISMENT";
const ARCHIVE_ADVERTISMENT = "advertisment:ARCHIVE_ADVERTISMENT";
const DISARCHIVE_ADVERTISMENT = "advertisment:DISARCHIVE_ADVERTISMENT";



const ADD_REVIEW = "review:ADD_REVIEW";
const GET_REVIEW_BY_ID = "review:GET_REVIEW_BY_ID";
const UPDATE_REVIEW = "review:UPDATE_REVIEW";
const DELETE_REVIEW = "review:DELETE_REVIEW";
const GET_ALL_REVIEW = "review:GET_ALL_REVIEW";


module.exports = {
    ADD_USER,
    GET_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_USER_BY_ID,
    ADD_TO_WISH_LIST,
    DELETE_FROM_WISH_LIST,
    GET_WISH_LIST,
    LIKE_PRODUCT,
    LIKE_VENDOR,
    LIKE_COLLECTION,
    GET_COLLECTION_LIST,
    GET_LIKED_PRODUCT,
    GET_LIKED_VENDOR,
    UPDATE_PROFILE_USER,
    DELETE_PROFILE_USER,
    GET_ALL_USER,
    ARCHIVE_USER,
    DISARCHIVE_USER,
    ARCHIVE_PROFILE,
    DISARCHIVE_PROFILE,
    SUBSCRIBE,
    GET_SELECTED_ITEMS,
    ADD_ITEM_TO_SELECTED_LIST,
    REMOVE_ITEM_FROM_SELECTED_LIST,
    GET_ALL_NOTIFICATION,
    ADD_VENDOR,
    GET_VENDOR,
    UPDATE_VENDOR,
    DELETE_VENDOR,
    UPDATE_PROFILE_VENDOR,
    DELETE_PROFILE_VENDOR,
    ARCHIVE_VENDOR,
    DISARCHIVE_VENDOR,
    ARCHIVE_PROFILE_VENDOR,
    DISARCHIVE_PROFILE_VENDOR,
    GET_VENDOR_BY_ID,
    GET__ALL_VENDOR,
    GET_MOST_LIKED_BRANDS,
    GET_ALL_CATEGORY_BY_VENDOR,
    VENDOR_SEARCH,
    ADD_ADMIN,
    GET_ADMIN,
    GET_ADMIN_BY_ID,
    UPDATE_ADMIN,
    DELETE_ADMIN,
    GET__ALL_ADMIN,
    ADD_PRODUCT,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    ARCHIVE_PRODUCT,
    DISARCHIVE_PRODUCT,
    GET_ALL_PRODUCT,
    GET_ALL_BRAND_ITEMS,
    GET_MOST_LIKED_ITEMS,
    GET_ALL_PRODUCT_BY_VENDOR,
    GET_ALL_PRODUCT_BY_CATEGORY,
    GET_ALL_PRODUCT_BY_COLLECTION,
    GET_ALL_PRODUCT_WITH_FILTER,
    PRODUCT_SEARCH,
    ADD_OFFER,
    GET_ALL_OFFER,
    ADD_CATEGORY,
    GET_CATEGORY_BY_ID,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    GET_ALL_CATEGORY,
    CATEGORY_SEARCH,
    ADD_COLLECTION,
    GET_COLLECTION_BY_ID,
    UPDATE_COLLECTION,
    DELETE_COLLECTION,
    ARCHIVE_COLLECTION,
    DISARCHIVE_COLLECTION,
    GET_ALL_COLLECTION,
    GET_ALL_Brand_COLLECTION,
    GET_MOST_LIKED_COLLECTIONS,
    COLLECTION_SEARCH,
    ADD_SALE,
    GET_SALE_BY_ID,
    UPDATE_SALE,
    DELETE_SALE,
    ARCHIVE_SALE,
    DISARCHIVE_SALE,
    GET_ALL_SALE,
    GET_MOST_LIKED_SALES,
    SALE_SEARCH,
    ADD_ADVERTISMENT,
    GET_ADVERTISMENTS_BY_ID,
    UPDATE_ADVERTISMENT,
    DELETE_ADVERTISMENT,
    ARCHIVE_ADVERTISMENT,
    DISARCHIVE_ADVERTISMENT,
    GET_ALL_ADVERTISMENT,
    ADD_REVIEW,
    GET_REVIEW_BY_ID,
    UPDATE_REVIEW,
    DELETE_REVIEW,
    GET_ALL_REVIEW,
}
